
swagger: '2.0'

info:
  version: "0.0.4"
  title: FaktoidAPI
  description: API lühikeste, potentsiaalselt mitmekeelsete faktide esitamiseks internetis. Kõik tulemused peavad olema UTF-8 kodeeringus.
  license:
    name: MIT
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /faktoid:
    get:
      description: Tagastab ühe juhusliku fakti liidese poolt maskeraaditud andmehulgast
      responses:
        '200':
          description: Kõik läks hästi
          schema:
            $ref: '#/definitions/faktoid'

  /faktoid/{filter}:
    get:
      description: Tagastab ühe juhusliku fakti liidese poolt maskeraaditud andmehulgast rakendades seejuures filtrit. Filtri semantika on määratud kliendi poolt. Laastutabloo puhul on filtriks omavalitsusüksuse EHAK kood. Kui fakte ei leitud, tagastatakse tühi järjend.
      parameters:
        - name: filter
          in: path
          description: Rakendatav filter
          required: true
          type: string
          
        - name: start
          in: query
          description: Alguskuupäev. Kui seatud, arvestatakse tulemuse leidmisel vaid kirjeid kas sama või hilisema kuupäevaga. 
          type: string
          format: date
        - name: end
          in: query
          description: Lõpukuupäev. Kui seatud, arvestatakse tulemuse leidmisel vaid kirjeid kas sama või varasema kuupäevaga. 
          type: string
          format: date
      responses:
        '200':
          description: Kõik läks hästi
          schema:
            $ref: '#/definitions/faktoid'
  /andmed:
    get:
      description: Tagastab JSON serialiseeringu kasutatavast andmehulgast. Kui päringud `/faktoid` URLidele tagastavad ühe juhusliku või filtreeritud päringu, siis siin tagastatakse terve andmehulk. Kui API maskeraadib madalama taseme APIt, on tulemus määratletud kui 'andmehulk, millele filtrit või juhuslikku valikut rakendatakse'. 
      responses:
        '200':
          description: Kõik läks hästi
  /meta:
    get:
      description: Tagastab metainfo andmestiku kohta
      responses:
        '200':
           description: Kõik läks hästi
           schema:
             type: object
             properties:
               uuendatud:
                 description: Andmete uuendamise kuupäev
                 type: string
                 format: date
               allikas:
                 description: Viide andmete algallikale
                 type: string
definitions:
  faktoid:
    type: object
    properties:
      keel:
        type: string
        description: Keele kolmetäheline kood ISO 639-2 alusel (https://en.wikipedia.org/wiki/ISO_639-2). Kood 'zxx' tähistab fakti, mille keel kas ei ole määratud või ei ole oluline.
      tekst:
        type: string
        description: Faktoid ise. Fakti pikkus ei ole määratletud kuid klient võib tema jaoks liigi pikki fakte kas ignoreerida või lühendada

          
    
    